### 이미지 업로드
POST http://118.222.92.10:1113/images/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="image1.png"
Content-Type: image/png

< /Users/gilzako/IdeaProjects/new_tankapp_backend/upload-servce-new/image1.png
--WebAppBoundary--

###todo: 다중 이미지 업로드 (다중 이미지도 가능)
POST http://118.222.92.10:1113/images/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="image1.png"
Content-Type: image/png

< /Users/gilzako/IdeaProjects/new_tankapp_backend/upload-servce-new/image1.png
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="image2.jpg"
Content-Type: image/jpeg

< /Users/gilzako/IdeaProjects/new_tankapp_backend/upload-servce-new/image2.png
--WebAppBoundary--
### 이미지 업로드
POST http://localhost:1113/images/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="image1.png"
Content-Type: image/png

< /Users/gilzako/IdeaProjects/new_tankapp_backend/upload-servce-new/image1.png
--WebAppBoundary--

