### 이미지 업로드 (정상 작동 방식)
POST http://localhost:1111/images/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="image1.png"
Content-Type: image/png

< /Users/gilzako/IdeaProjects/new_tankapp_backend/upload-servce-new/image1.png
--WebAppBoundary--
