### GET 전체 차량 목록
GET http://localhost:1112/api/vehicles
Authorization: supertoken1234
Content-Type: application/json

####
POST http://localhost:1112/api/vehicles
Authorization: supertoken1234
Content-Type: application/json

{
  "cMngNo": "1818",
  "carCode": "005",
  "carName": "신차량",
  "carType": "1",
  "iotCode": "00090004",
  "swCode": "S001",
  "carMaker": "현대",
  "carInsure": "삼성화재",
  "carInsureTurm": "2025-12",
  "carMemo": "신규 등록"
}
####
PUT http://localhost:1112/api/vehicles
Authorization: supertoken1234
Content-Type: application/json

{
  "cMngNo": "0009",
  "carCode": "004",
  "carName": "수정된차량",
  "carType": "1",
  "iotCode": "00090004",
  "swCode": "S001",
  "carMaker": "기아",
  "carInsure": "DB손해보험",
  "carInsureTurm": "2026-01",
  "carMemo": "메모 수정됨"
}
####

DELETE http://localhost:1112/api/vehicles?cMngNo=0009&carCode=004
Authorization: supertoken1234



##############

### 차량 리스트 조회 (업체코드: 0009)
GET http://localhost:1112/api/vehicles?cMngNo=1818
Accept: application/json
Authorization: supertoken1234
