### 회원가입 요청
POST http://localhost:9081/v1/signup
Content-Type: application/json

{
  "userPhone": "0102222222",
  "userPass": "1",
  "userName": "고은하2",
  "userPosition": "대리2",
  "cMngName": "고은하컴패니2"
}
